'use strict';
(()=>{
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),A=()=>window.PMS_ADMIN;
const nav=$('#tabs'),content=$('#workspace .content');
for(const [id,label]of [['feedback','Corrections'],['analytics','Usage counts'],['security','Security']]){const b=document.createElement('button');b.dataset.tab=id;b.textContent=label;nav.append(b);const s=document.createElement('section');s.id=id;s.className='panel';s.hidden=true;content.append(s);}
$('#feedback').innerHTML='<p class="muted">Review submitted corrections, then edit the affected place or page. Reviewing does not change the guide automatically.</p><div id="feedback-list" class="records"></div>';
$('#analytics').innerHTML='<div class="card"><h2>Aggregate usage · last 30 days</h2><p>Counts only from visitors who opt in. Reloads can count again; these are not unique visitors. No search terms, account IDs or device identifiers are stored in these counts.</p><div id="metric-list"></div></div>';
$('#security').innerHTML='<div class="card"><h2>Administrator two-step verification</h2><p id="factor-state">Checking…</p><p>Use an authenticator app. Enabling or disabling verification signs out existing sessions. Save your recovery codes offline.</p><form id="factor-form"><label>Current password<input name="password" type="password" minlength="10" maxlength="72" autocomplete="current-password" required></label><button type="button" id="factor-begin">Start setup</button><div id="factor-setup" hidden><p>Add an account manually in your authenticator: time-based, SHA1, 6 digits, 30 seconds.</p><code id="factor-secret" class="security-key"></code></div><label>Authenticator / recovery code<input name="otp" autocomplete="one-time-code" maxlength="30"></label><div class="actions"><button id="factor-confirm" type="submit" hidden>Enable verification</button><button id="factor-disable" type="button" class="secondary" hidden>Disable verification</button></div><p id="factor-result" class="plus-status" role="status"></p></form></div>';
const extra=document.createElement('fieldset');extra.innerHTML='<legend>Date exceptions & verification</legend><label>Special dates<textarea name="exceptions_text" rows="4" placeholder="2026-12-25 | closed | Public holiday\n2026-12-26 | 09:00-12:00, 14:00-17:00 | Special hours"></textarea></label><p class="muted">One date per line: YYYY-MM-DD | closed or HH:MM-HH:MM | note. Applies only on that Malaysia date, then weekly hours return automatically. Exceptions override temporary status.</p><label>Verification source<input name="verification_source" maxlength="300" placeholder="Counter notice / organiser / official notice"></label><label>Checked by<input name="verification_by" maxlength="120"></label><label>Date checked<input name="verification_date" type="date"></label><p class="muted">Older than 90 days is flagged for review; it does not mean the information is incorrect.</p>';
$('#place-fields').append(extra);
const versions=document.createElement('button');versions.type='button';versions.className='secondary';versions.id='version-history';versions.textContent='Version history';$('#content-form').append(versions);
const dlg=document.createElement('dialog');dlg.id='plus-dialog';document.body.append(dlg);let current=null;
window.PMS_PLUS={
fill(f,p,r){current=r;extra.hidden=f.elements.kind.value!=='place';f.elements.exceptions_text.value=(p.exceptions||[]).map(v=>v.date+' | '+(v.slots.length?v.slots.map(s=>s.a+'-'+s.b).join(', '):'closed')+' | '+(v.note||'')).join('\n');for(const k of ['source','by','date'])f.elements['verification_'+k].value=p.verification?.[k]||'';f.elements.verification_date.max=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuala_Lumpur'}).format(new Date());versions.hidden=!r;},
collect(f,p){if(f.elements.kind.value!=='place')return;p.verification=Object.fromEntries(['source','by','date'].map(k=>[k,f.elements['verification_'+k].value.trim()]));p.exceptions=f.elements.exceptions_text.value.split('\n').filter(s=>s.trim()).map(line=>{const [date,hours,...notes]=line.split('|').map(s=>s.trim());if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!hours)throw Error('Use YYYY-MM-DD | closed or HH:MM-HH:MM | note.');return{date,note:notes.join(' | '),slots:hours.toLowerCase()==='closed'?[]:hours.split(',').map(s=>{const m=s.trim().match(/^(\d{2}:\d{2})-(\d{2}:\d{2})$/);if(!m)throw Error('Invalid special-date hours.');return{a:m[1],b:m[2],label:''};})};});},
async onTab(tab){
if(tab==='feedback'){const r=await A().api('admin_feedback');$('#feedback-list').innerHTML=r.feedback.map(f=>`<article class="record"><span class="badge">${esc(f.status)}</span><h3>${esc(f.target)}</h3><small>${esc(f.nickname)} · ${esc(f.created_at)} UTC</small><p>${esc(f.message)}</p>${/^https:\/\//.test(f.evidence_url)?`<a href="${esc(f.evidence_url)}" target="_blank" rel="noopener noreferrer">Evidence link</a>`:''}<p>${esc(f.review_note||'')}</p>${f.status==='pending'?`<button data-feedback="${Number(f.id)}" data-state="reviewed">Mark reviewed</button> <button data-feedback="${Number(f.id)}" data-state="dismissed" class="secondary">Dismiss</button>`:''}</article>`).join('')||'<p>No corrections submitted yet.</p>';}
if(tab==='analytics'){const r=await A().api('admin_metrics');$('#metric-list').innerHTML=r.metrics.length?'<table class="plus-table"><thead><tr><th>Type</th><th>Page / place</th><th>Count</th></tr></thead><tbody>'+r.metrics.map(m=>`<tr><td>${esc(m.kind)}</td><td>${esc(m.target)}</td><td>${Number(m.hits)}</td></tr>`).join('')+'</tbody></table>':'<p>No opted-in usage counts yet.</p>';}
if(tab==='security'){const r=await A().api('factor_status');$('#factor-state').textContent=r.enabled?'Verification is enabled.':'Verification is not enabled.';$('#factor-begin').hidden=r.enabled;$('#factor-disable').hidden=!r.enabled;$('#factor-confirm').hidden=true;$('#factor-setup').hidden=true;$('#factor-form').reset();$('#factor-secret').textContent='';$('#factor-result').textContent='';}
}};
document.addEventListener('click',e=>{const b=e.target.closest('[data-feedback]');if(b)A().run(b,async()=>{const note=prompt('Review note:','');if(note===null)return;await A().api('admin_review_feedback',{id:Number(b.dataset.feedback),status:b.dataset.state,note});await window.PMS_PLUS.onTab('feedback');A().say('Correction reviewed. Edit content separately when needed.');});});
versions.onclick=()=>A().run(versions,async()=>{if(!current)return;const r=await A().api('admin_versions',undefined,{id:current.id});dlg.innerHTML='<h2>Content version history</h2><p>Restoring creates a new revision. Published historical content becomes public again.</p>'+r.versions.map(v=>`<div class="audit-row"><strong>Revision ${Number(v.revision)}</strong> · ${esc(v.status)}<br><small>${esc(v.nickname||'Import')} · ${esc(v.created_at)} UTC</small><br><button data-restore="${Number(v.revision)}" class="secondary">Restore this revision</button></div>`).join('')+'<p><button data-close-plus>Close</button></p>';dlg.showModal();});
dlg.onclick=e=>{const close=e.target.closest('[data-close-plus]');if(close){dlg.close();return;}const b=e.target.closest('[data-restore]');if(b)A().run(b,async()=>{if(!confirm('Restore this revision and its publication status?'))return;await A().api('admin_restore_version',{id:current.id,revision:Number(b.dataset.restore),expected_revision:current.revision});dlg.close();$('#content-dialog').close();await A().refresh();A().say('Historical content restored as a new revision.');});};
$('#factor-begin').onclick=e=>A().run(e.target,async()=>{const f=$('#factor-form');if(!f.reportValidity())return;const r=await A().api('factor_begin',{password:f.elements.password.value});$('#factor-secret').textContent=r.secret;$('#factor-setup').hidden=false;$('#factor-confirm').hidden=false;$('#factor-result').textContent='Enter the current 6-digit code within 10 minutes.';});
$('#factor-form').onsubmit=e=>{e.preventDefault();A().run($('#factor-confirm'),async()=>{const r=await A().api('factor_enable',Object.fromEntries(new FormData(e.currentTarget)));dlg.innerHTML='<h2>Save your recovery codes now</h2><p>Each code works once. Keep these offline. Codes are shown only once.</p><pre class="security-key"></pre><p>All sessions are signed out. Wait for a fresh authenticator code before logging in again.</p><button data-close-plus>I have saved the codes</button>';dlg.querySelector('pre').textContent=r.recovery_codes.join('\n');A().logout();dlg.showModal();});};
$('#factor-disable').onclick=e=>A().run(e.target,async()=>{if(!confirm('Disable verification and sign out all sessions?'))return;await A().api('factor_disable',Object.fromEntries(new FormData($('#factor-form'))));A().logout();A().say('Verification disabled. Please log in again.');});
})();
