'use strict';
(()=>{
const $=s=>document.querySelector(s),base=window.PMS_FORUM_CONFIG.api;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let token='',user=null,tab='dashboard',records=[],media=[],users=[],forum=[],pages={users:1,forum:1,audit:1},seed=null;
try{token=sessionStorage.getItem('pms-forum-token')||'';}catch{}
const say=v=>{$('#notice').textContent=v;};
function sessionOff(){token='';user=null;try{sessionStorage.removeItem('pms-forum-token');}catch{}$('#workspace').hidden=true;$('#login-panel').hidden=false;$('#logout').hidden=true;$('#user-form').reset();$('#content-form').reset();$('#content-dialog').close();['#user-list','#audit-list','#media-list','#place-list','#page-list','#forum-list','#report-list'].forEach(s=>{$(s).replaceChildren();});}
async function api(action,data,params={}){const url=new URL(base);url.searchParams.set('action',action);Object.entries(params).forEach(([k,v])=>url.searchParams.set(k,v));const headers={};if(token)headers.Authorization='Bearer '+token;if(data!==undefined&&!(data instanceof FormData))headers['Content-Type']='application/json';const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),45000);try{const r=await fetch(url,{method:data===undefined?'GET':'POST',headers,body:data===undefined?undefined:data instanceof FormData?data:JSON.stringify(data),cache:'no-store',credentials:'omit',signal:controller.signal});const j=await r.json();if(!r.ok||!j.ok){if(r.status===401)sessionOff();throw Error(j.error||'Request failed.');}return j;}catch(e){throw Error(e.name==='AbortError'?'Request timed out. Check your connection and retry.':e instanceof TypeError?'Could not connect to the backend.':e.message);}finally{clearTimeout(timer);}}
async function run(button,fn){if(button?.disabled)return;if(button)button.disabled=true;try{await fn();}catch(e){say(e.message);}finally{if(button)button.disabled=button.dataset.locked==='true';}}
function authView(){$('#login-panel').hidden=true;$('#workspace').hidden=false;$('#logout').hidden=false;$('#admin-name').textContent=user.nickname;}
function imageURL(id){const u=new URL(base);u.searchParams.set('action','cms_media_file');u.searchParams.set('id',id);return u.href;}
function localized(v){return v?.en||v?.ms||v?.zh||'';}
async function catalog(){const r=await api('admin_cms');records=r.records;const m=await api('admin_media');media=m.media;renderContent();}
function renderContent(){for(const kind of ['place','page']){let rows=records.filter(r=>r.kind===kind);if(kind==='place'){const q=$('#place-search').value.toLowerCase();rows=rows.filter(r=>(r.record_key+' '+localized(r.payload.title)).toLowerCase().includes(q));}$('#'+(kind==='place'?'place':'page')+'-list').innerHTML=rows.map(r=>`<article class="record"><h3>${esc(localized(r.payload.title))}</h3><span class="badge">${esc(r.status)}</span>${kind==='place'&&(!r.payload.verification?.date||(Date.now()-new Date(r.payload.verification.date))/86400000>90)?'<span class="badge">Needs verification</span>':''}<small>${esc(r.record_key)} · revision ${Number(r.revision)}</small><p>${esc(localized(r.payload.body).slice(0,180))}</p><button data-edit-content="${Number(r.id)}">Edit</button></article>`).join('')||'<p>No entries yet. Import existing places or create a new entry.</p>';}}
async function load(){
 if(window.PMS_PLUS)await window.PMS_PLUS.onTab(tab);
 if(tab==='dashboard'){const r=await api('admin_dashboard');const names={users:'Accounts',active_users:'Active accounts',posts:'Forum posts',reports:'Pending reports',published_content:'Published guide entries',photos:'Uploaded photos',subscribers:'Subscribed devices'};$('#stats').innerHTML=Object.entries(r.stats).map(([k,n])=>`<div class="stat"><span>${esc(names[k]||k)}</span><strong>${Number(n)}</strong></div>`).join('');$('#push-health').textContent=r.push_ready?'Notification service configured. A real-device test is still required.':'Notification service needs configuration.';}
 if(tab==='users'){const r=await api('admin_users',undefined,{q:$('#user-search').value,page:pages.users});users=r.users;$('#user-list').innerHTML=users.map(u=>`<div class="list-row"><button data-edit-user="${Number(u.id)}" class="secondary">Edit</button><strong>${esc(u.nickname)}</strong><br><small>${esc(u.email)}</small><br><span class="badge">${esc(u.role)}</span><span class="badge">${esc(u.status)}</span></div>`).join('')||'<p>No accounts found.</p>';pager('users',r.has_more);}
 if(['places','pages'].includes(tab))await catalog();
 if(tab==='media'){media=(await api('admin_media')).media;$('#media-list').innerHTML=media.map(m=>`<article class="record">${m.status==='published'?`<img src="${esc(imageURL(m.id))}" alt="${esc(m.caption)}" loading="lazy">`:'<p>Hidden photo</p>'}<small>#${Number(m.id)} · ${Math.round(m.size_bytes/1024)} KB</small><input data-caption="${Number(m.id)}" value="${esc(m.caption)}" maxlength="200" aria-label="Photo caption"><div class="actions"><button data-save-photo="${Number(m.id)}">Save caption</button><button class="secondary" data-toggle-photo="${Number(m.id)}">${m.status==='published'?'Hide':'Publish'}</button></div></article>`).join('')||'<p>No uploaded photos yet.</p>';}
 if(tab==='forum'){const r=await api('admin_forum',undefined,{q:$('#forum-search').value,status:$('#forum-status').value,page:pages.forum});forum=r.posts;$('#forum-list').innerHTML=forum.map(p=>`<article class="record"><h3>${esc(p.title)}</h3><small>#${Number(p.id)} · ${esc(p.nickname)}${p.is_anonymous?' (anonymous publicly)':''}</small><span class="badge">${esc(p.status)}</span><p>${esc(p.body.slice(0,400))}</p><div class="actions"><button data-moderate="${Number(p.id)}">${p.status==='hidden'?'Restore':'Hide'}</button><button class="secondary" data-pin="${Number(p.id)}">${p.is_pinned?'Unpin':'Pin'}</button><a href="community.html?post=${Number(p.id)}" target="_blank" rel="noopener">View & comments ↗</a></div></article>`).join('')||'<p>No posts found.</p>';pager('forum',r.has_more);const reports=(await api('admin_reports')).reports;$('#report-list').innerHTML=reports.map(r=>`<article class="record"><h3>${esc(r.title)}</h3><p>${esc(r.reason||'Reported content')}</p>${r.comment_body?`<p>${esc(r.comment_body)}</p>`:''}<button data-report="${Number(r.id)}" data-report-state="resolved">Resolve</button> <button class="secondary" data-report="${Number(r.id)}" data-report-state="dismissed">Dismiss</button></article>`).join('')||'<p>No pending reports.</p>';}
 if(tab==='audit'){const r=await api('admin_audit',undefined,{page:pages.audit});$('#audit-list').innerHTML=r.logs.map(a=>`<div class="audit-row"><strong>${esc(a.action)}</strong> · ${esc(a.target)}<br><small>${esc(a.nickname||'Former account')} · ${esc(a.created_at)} UTC</small><p>${esc(a.details)}</p></div>`).join('')||'<p>No activity recorded yet.</p>';pager('audit',r.has_more);}
}
function pager(name,more){for(const [dir,disabled]of [['prev',pages[name]<=1],['next',!more]]){const b=$('#'+name+'-'+dir);b.dataset.locked=String(disabled);b.disabled=disabled;}}
$('#tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(!b)return;tab=b.dataset.tab;document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==tab);document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#section-title').textContent=b.textContent;run($('#refresh'),load);};
$('#refresh').onclick=e=>run(e.target,load);
$('#login-form').onsubmit=e=>{e.preventDefault();const form=e.currentTarget;run(form.querySelector('button'),async()=>{const r=await api('login',Object.fromEntries(new FormData(form)));token=r.token;if(r.user.role!=='admin'){await api('logout',{},{}).catch(()=>{});sessionOff();throw Error('This account is not an administrator.');}token=r.token;user=r.user;try{sessionStorage.setItem('pms-forum-token',token);}catch{}form.reset();authView();await load();say('Logged in.');});};
$('#logout').onclick=e=>run(e.target,async()=>{try{await api('logout',{});}finally{sessionOff();say('Logged out.');}});
function userEditor(u=null){const f=$('#user-form');f.reset();for(const k of ['id','email','nickname','role','status'])if(u)f.elements[k].value=u[k];f.elements.email.readOnly=!!u;f.elements.password.required=!u;$('#new-password-label').hidden=!!u;$('#reset-password').disabled=!u;$('#user-editor-title').textContent=u?'Edit account #'+u.id:'New account';}
$('#new-user').onclick=()=>userEditor();$('#find-users').onclick=e=>{pages.users=1;run(e.target,load);};
$('#user-form').onsubmit=e=>{e.preventDefault();run(e.currentTarget.querySelector('button[type=submit],button:not([type])'),async()=>{const f=e.currentTarget,d=Object.fromEntries(new FormData(f));delete d.reset_password;if(d.id)delete d.password;await api('admin_save_user',d);f.elements.password.value='';await load();say('Account saved. Changed permissions revoke existing sessions.');});};
$('#reset-password').onclick=e=>run(e.target,async()=>{const f=$('#user-form'),pw=f.elements.reset_password;if(!pw.reportValidity()||!pw.value)throw Error('Enter a new password of at least 10 characters.');if(!confirm('Reset this password and log this account out on all devices?'))return;const r=await api('admin_reset_password',{id:f.elements.id.value,password:pw.value});pw.value='';if(r.relogin){sessionOff();say('Password updated. Log in again.');}else say('Password updated. All sessions revoked.');});
$('#find-posts').onclick=e=>{pages.forum=1;run(e.target,load);};$('#place-search').oninput=renderContent;
for(const n of ['users','forum','audit'])for(const dir of ['prev','next'])$('#'+n+'-'+dir).onclick=e=>{pages[n]+=dir==='next'?1:-1;run(e.target,load);};
async function getSeed(){if(!seed){const r=await fetch('cms-seed.json',{cache:'no-store'});if(!r.ok)throw Error('Guide seed file is missing.');seed=await r.json();}return seed;}
$('#import-guide').onclick=e=>run(e.target,async()=>{if(!confirm('Import original guide places? Existing entries are kept.'))return;const r=await api('admin_import_cms',{records:(await getSeed()).records});await load();say(r.inserted+' places imported.');});
const slots=['guide-preparation','arrival-route','orientation-clothes','checklist','guide-hostel','hostel-blocks','hostel-facilities','hostel-living','holiday-departure','guide-digital','campus-network','mobile-signal','student-systems','timetable-guide','guide-clubs','club-joining','guide-support','contacts','faq','life','outing-guide','about'];
$('#content-form').elements.slot.innerHTML=slots.map(k=>`<option value="${k}">${k}</option>`).join('');
const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];$('#weekly-hours').innerHTML=days.map((day,i)=>`<label class="hours-row">${day}<input data-hours="${i}" placeholder="08:00-12:00, 14:00-17:00" aria-label="${day} hours"></label>`).join('')+'<p class="muted">Empty = closed. Use 24-hour time; split breaks with commas. Overnight hours must be split at midnight (end at 23:59).</p>';
async function editor(kind,r=null){await catalog();const seedData=await getSeed();const f=$('#content-form');f.reset();f.elements.kind.value=kind;f.elements.revision.value=r?.revision||0;f.elements.record_key.value=r?.record_key||'';f.elements.record_key.readOnly=!!r;$('#place-fields').hidden=kind!=='place';$('#page-fields').hidden=kind!=='page';$('#content-title').textContent=kind==='place'?'Place & opening hours':'Page content';
 f.elements.media_id.innerHTML='<option value="">No uploaded photo</option>'+media.filter(m=>m.status==='published').map(m=>`<option value="${Number(m.id)}">#${Number(m.id)} ${esc(m.caption)}</option>`).join('');f.elements.photo_path.innerHTML='<option value="">No bundled photo</option>'+seedData.photos.map(k=>`<option value="${esc(k)}">${esc(k)}</option>`).join('');
 const p=r?.payload||{};for(const k of ['title','body','note'])for(const l of ['en','ms','zh'])f.elements[k+'_'+l].value=p[k]?.[l]||'';
 for(const k of ['media_id','photo_path','category','x','y','closure','slot','order'])if(p[k]!==undefined)f.elements[k].value=p[k]??'';f.elements.status.value=r?.status||'draft';f.elements.replace.checked=!!p.replace;f.elements.custom_schedule.checked=p.schedule!==null&&p.schedule!==undefined;
 document.querySelectorAll('[data-hours]').forEach(x=>{x.value=(p.schedule?.[Number(x.dataset.hours)]||[]).map(s=>s.a+'-'+s.b).join(', ');});if(window.PMS_PLUS)window.PMS_PLUS.fill(f,p,r);$('#content-dialog').showModal();}
$('#close-editor').onclick=()=>$('#content-dialog').close();
$('#content-form').onsubmit=e=>{e.preventDefault();run(e.currentTarget.querySelector('button:not([type])'),async()=>{const f=e.currentTarget,g=k=>f.elements[k].value,kind=g('kind'),p={};for(const k of ['title','body','note'])p[k]=Object.fromEntries(['en','ms','zh'].map(l=>[l,g(k+'_'+l)]));p.media_id=g('media_id')?Number(g('media_id')):null;
 if(kind==='place'){for(const k of ['category','closure','photo_path'])p[k]=g(k);p.x=g('x')===''?null:Number(g('x'));p.y=g('y')===''?null:Number(g('y'));p.schedule=f.elements.custom_schedule.checked?[...document.querySelectorAll('[data-hours]')].map(x=>x.value.trim()?x.value.split(',').map(s=>{const m=s.trim().match(/^(\d{2}:\d{2})\s*-\s*(\d{2}:\d{2})$/);if(!m)throw Error('Use HH:MM-HH:MM, separated by commas.');const old=records.find(r=>r.record_key===g('record_key'))?.payload.schedule?.[Number(x.dataset.hours)]?.find(slot=>slot.a===m[1]&&slot.b===m[2]);return{a:m[1],b:m[2],label:old?.label||''};}):[]):null;}else{p.slot=g('slot');p.replace=f.elements.replace.checked;p.order=Number(g('order'));}
 if(window.PMS_PLUS)window.PMS_PLUS.collect(f,p);await api('admin_save_cms',{kind,record_key:g('record_key'),revision:Number(g('revision')),status:g('status'),payload:p});$('#content-dialog').close();await catalog();say('Content saved. Published changes appear when visitors reload the website.');});};
$('#upload-form').onsubmit=e=>{e.preventDefault();run(e.currentTarget.querySelector('button'),async()=>{const f=e.currentTarget,file=f.elements.photo.files[0];if(!file||file.size>4*1024*1024)throw Error('Choose a photo smaller than 4 MB.');const data=new FormData();data.append('photos[]',file);data.append('caption',f.elements.caption.value);await api('admin_upload_media',data);f.reset();await load();say('Photo uploaded. Select it in a place or page editor.');});};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.editUser)userEditor(users.find(u=>Number(u.id)===Number(b.dataset.editUser)));
 if(b.dataset.new)run(b,()=>editor(b.dataset.new));if(b.dataset.editContent){const r=records.find(r=>Number(r.id)===Number(b.dataset.editContent));run(b,()=>editor(r.kind,r));}
 const mid=b.dataset.savePhoto||b.dataset.togglePhoto;if(mid)run(b,async()=>{const m=media.find(m=>Number(m.id)===Number(mid));const status=b.dataset.togglePhoto?(m.status==='published'?'hidden':'published'):m.status;if(status==='hidden'&&!confirm('Hide this photo everywhere it is used?'))return;await api('admin_save_media',{id:Number(mid),caption:$(`[data-caption="${Number(mid)}"]`).value,status});await load();say('Photo updated.');});
 const pid=b.dataset.moderate||b.dataset.pin;if(pid)run(b,async()=>{const p=forum.find(p=>Number(p.id)===Number(pid));const status=b.dataset.moderate?(p.status==='published'?'hidden':'published'):p.status;if(!confirm('Update this post?'))return;await api('moderate_post',{id:Number(pid),status,is_pinned:b.dataset.pin?!p.is_pinned:!!p.is_pinned});await load();say('Post updated.');});
 if(b.dataset.report)run(b,async()=>{const note=prompt('Review note (optional):','');if(note===null)return;await api('resolve_report',{id:Number(b.dataset.report),status:b.dataset.reportState,note});await load();say('Report reviewed.');});
});
window.PMS_ADMIN={api,run,say,refresh:load,logout:sessionOff,records:()=>records,user:()=>user};userEditor();(async()=>{if(!token)return;try{const r=await api('me');if(r.user.role!=='admin'){sessionOff();say('Administrator account required.');return;}user=r.user;authView();await load();}catch(e){say(e.message);}})();
})();
