'use strict';
(()=>{
const $=s=>document.querySelector(s),lang=()=>{try{return localStorage.getItem('pms-language')||'en';}catch{return'en';}},L=(en,ms,zh)=>({en,ms,zh}[lang()]||en),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(action,data){const u=new URL(window.PMS_FORUM_CONFIG.api);u.searchParams.set('action',action);const headers={};try{const t=sessionStorage.getItem('pms-forum-token');if(t)headers.Authorization='Bearer '+t;}catch{}if(data)headers['Content-Type']='application/json';const r=await fetch(u,{method:data?'POST':'GET',headers,body:data?JSON.stringify(data):undefined,credentials:'omit',cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Connection unavailable');return j;}
for(const id of ['login-form','auth-form']){const f=$('#'+id);if(!f||f.elements.otp)continue;const label=document.createElement('label');label.setAttribute('data-no-translate','');label.textContent=L('Admin authenticator / recovery code (if enabled)','Kod pengesah / pemulihan pentadbir (jika aktif)','管理员验证码 / 恢复码（已启用时填写）');const input=document.createElement('input');input.name='otp';input.autocomplete='one-time-code';input.maxLength=30;label.append(input);f.querySelector('[type=submit],button')?.before(label);}
const consent=document.createElement('div');consent.className='privacy-counts';consent.setAttribute('data-no-translate','');consent.innerHTML='<label><input type="checkbox"> '+L('Allow anonymous usage counts (optional)','Benarkan kiraan penggunaan tanpa identiti (pilihan)','允许匿名使用次数统计（可选）')+'</label><span>'+L('Page and place counts only. No search text, account or device IDs.','Kiraan halaman dan tempat sahaja. Tiada teks carian, ID akaun atau peranti.','仅统计页面和地点次数，不收集搜索词、账号或设备标识。')+'</span>';document.querySelector('footer')?.before(consent);let opted=false;try{opted=localStorage.getItem('pms-counts-opt-in')==='yes';}catch{}consent.querySelector('input').checked=opted;
const page=location.pathname.endsWith('admin.html')?'admin':location.pathname.endsWith('campus.html')?'campus':location.pathname.endsWith('community.html')?'community':'guide';
const count=(kind,target)=>{if(opted)api('metric',{kind,target}).catch(()=>{});};
consent.querySelector('input').onchange=e=>{opted=e.target.checked;try{localStorage.setItem('pms-counts-opt-in',opted?'yes':'no');}catch{}if(opted)count('page',page);};count('page',page);
if(page!=='guide')return;
const today=document.createElement('section');today.id='today-pms';today.className='plus-card';today.setAttribute('data-no-translate','');$('#explore .intro')?.after(today);let updates=[],updateError=false;
function drawToday(){const date=klClock().date;const open=places.filter(p=>matchesPlace(p,'')&&todaySchedule(p[0]).state==='open');const unknown=places.filter(p=>matchesPlace(p,'')&&todaySchedule(p[0]).state==='unknown').length;
today.innerHTML=`<h2>Hari Ini di PMS <small>· ${esc(date)} · MYT</small></h2><div class="plus-grid"><div><h3>${L('Open by timetable','Dibuka mengikut jadual','按时间表开放')}</h3><p>${open.length} ${L('places','tempat','个地点')} · ${unknown} ${L('unconfirmed','belum disahkan','时间待确认')}</p>${open.length?'<ul>'+open.slice(0,5).map(p=>`<li><button class="soft-button" data-today-place="${esc(p[0])}">${esc(p[0])}</button></li>`).join('')+'</ul>':`<p>${L('No open places confirmed.','Tiada tempat dibuka yang disahkan.','暂无已确认的开放地点。')}</p>`}<small>${L('Timetables are not live availability.','Jadual bukan status masa nyata.','时间表不等于实时营业状态。')}</small></div><div><h3>${L('Today’s updates & events','Info & aktiviti hari ini','今日资讯与活动')}</h3>${updateError?`<p>${L('Updates unavailable. Open Campus Updates to retry.','Info tidak dapat dimuatkan. Cuba di Info Kampus.','资讯暂时无法读取，请到校园资讯页面重试。')}</p>`:updates.length?updates.slice(0,3).map(u=>`<p><a href="campus.html?update=${Number(u.id)}">${esc(u.title)}</a></p>`).join(''):`<p>${L('No active entries today.','Tiada maklumat aktif hari ini.','今日暂无有效资讯。')}</p>`}<a href="campus.html">${L('All campus updates','Semua info kampus','全部校园资讯')}</a></div><div><h3>${L('Lost & Found','Lost & Found','失物招领')}</h3><p>${L('Lost something or found an item? Check the community board.','Barang hilang atau dijumpai? Semak papan komuniti.','遗失或捡到物品？到社区查看。')}</p><a href="community.html?category=lost_found">${L('Open Lost & Found','Buka Lost & Found','打开失物招领')}</a></div></div>`;}
today.onclick=e=>{const b=e.target.closest('[data-today-place]');if(!b)return;const i=places.findIndex(p=>p[0]===b.dataset.todayPlace);if(i>=0){selected=i;render();$('#detail').scrollIntoView({behavior:'smooth',block:'center'});count('place',places[i][0]);}};
api('updates').then(r=>{const d=klClock().date;updates=r.updates.filter(u=>{const start=new Date(u.starts_at.replace(' ','T')+'Z'),end=new Date(u.ends_at.replace(' ','T')+'Z');return klClock(start).date<=d&&klClock(end).date>=d;});drawToday();}).catch(()=>{updateError=true;drawToday();});drawToday();document.addEventListener('pms-cms-updated',drawToday);setInterval(drawToday,60000);$('#language-select')?.addEventListener('change',()=>setTimeout(drawToday,0));
document.addEventListener('click',e=>{const b=e.target.closest('#directory [data-id],#pins [data-id]');if(b){const p=places[Number(b.dataset.id)];if(p)count('place',p[0]);}});let searchTimer;$('#place-search')?.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{if($('#place-search').value.trim()&&!places.some(p=>matchesPlace(p,$('#place-search').value.trim())))count('search_miss','no_results');},1500);});
const feedback=document.createElement('details');feedback.className='plus-compact';feedback.setAttribute('data-no-translate','');feedback.innerHTML='<summary>'+L('Submit correction for administrator review','Hantar pembetulan untuk semakan pentadbir','提交更正，由管理员审核')+'</summary><p>'+L('Log in on Community first. The original copy/share option remains below.','Log masuk di Komuniti dahulu. Pilihan salin/kongsi asal masih tersedia.','请先在社区登录。原有复制 / 分享方式仍保留。')+'</p><form id="correction-form"><label>'+L('Correction / source','Pembetulan / sumber','更正内容 / 来源')+'<textarea name="message" minlength="10" maxlength="4000" rows="4" required></textarea></label><label>'+L('Evidence link (HTTPS, optional)','Pautan bukti (HTTPS, pilihan)','证据链接（HTTPS，可选）')+'<input name="evidence_url" type="url" maxlength="1000"></label><button type="submit">'+L('Submit for review','Hantar untuk semakan','提交审核')+'</button> <button id="my-corrections" type="button">'+L('My corrections','Pembetulan saya','我的更正')+'</button><p id="correction-status" class="plus-status" role="status"></p></form><div id="correction-history"></div>';
// A nested form is invalid: place the live form beside the original manual form.
$('#report-dialog')?.append(feedback);
$('#correction-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('[type=submit]');b.disabled=true;try{const data=Object.fromEntries(new FormData(f));data.target=$('#report-place').value;await api('feedback_submit',data);f.reset();$('#correction-status').textContent=L('Submitted. The guide changes only after administrator review and editing.','Dihantar. Panduan berubah selepas semakan dan suntingan pentadbir.','已提交。管理员审核并编辑后，指南才会更新。');}catch(err){$('#correction-status').textContent=err.message;}finally{b.disabled=false;}};
$('#my-corrections').onclick=async()=>{try{const r=await api('feedback_my');$('#correction-history').innerHTML=r.feedback.map(f=>`<div class="verification"><strong>${esc(f.target)} · ${esc(f.status)}</strong><p>${esc(f.message)}</p><p>${esc(f.review_note||'')}</p></div>`).join('')||L('No corrections yet.','Belum ada pembetulan.','暂无更正记录。');}catch(err){$('#correction-status').textContent=err.message;}};
})();
