const $=id=>document.getElementById(id);
$('place-search').addEventListener('input',e=>{searchQuery=e.target.value;render()});
$('clear-search').onclick=()=>{searchQuery='';filter='all';$('place-search').value='';document.querySelectorAll('[data-filter]').forEach(b=>{const active=b.dataset.filter==='all';b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});render();$('place-search').focus()};
const checklistGroups=[['报到文件',['核对录取通知书、报到日期和地点','按当届清单准备身份证明、所需原件与复印件','准备通知中要求的表格、照片和付款凭证','保存校方报到通知及联络方式']],['宿舍用品',['确认宿舍安排及允许携带的物品','准备床上用品、毛巾及个人护理用品','准备衣架、洗衣用品及所需支付方式','准备有领衣服、长裤及包鞋','带扫把、垃圾桶、垃圾袋等打扫用品','准备自己习惯的枕头','至少准备两套白色衬衫，迎新活动时需要穿。']],['报到与第一周',['安排交通并确认报到地点','按校方安排办理报到与住宿手续','查看课表、说明会及所属科系安排','阅读正式校园与宿舍条例','认识 HEP、图书馆、食堂及求助渠道']]];
const storageKey='pms-new-student-checklist-v1';let checked={};try{const saved=JSON.parse(localStorage.getItem(storageKey)||'{}');if(saved&&typeof saved==='object'&&!Array.isArray(saved))checked=saved}catch{};
let itemCount=0;$('check-items').innerHTML=checklistGroups.map(([name,items],g)=>`<fieldset><legend>${name}</legend>${items.map((text,j)=>{itemCount++;const id=`${g}-${j}`;return `<label class="check-item"><input type="checkbox" data-check="${id}" ${checked[id]===true?'checked':''}><span>${text}</span></label>`}).join('')}</fieldset>`).join('');
function updateChecks(){const done=document.querySelectorAll('[data-check]:checked').length;$('check-progress').textContent=`已完成 ${done} / ${itemCount} 项`;try{localStorage.setItem(storageKey,JSON.stringify(checked));$('storage-note').textContent='已保存在当前浏览器。'}catch{$('storage-note').textContent='当前浏览器无法保存，关闭页面后勾选可能丢失。'}}
document.querySelectorAll('[data-check]').forEach(el=>el.onchange=()=>{checked[el.dataset.check]=el.checked;updateChecks()});$('reset-checklist').onclick=()=>{if(!confirm(tr('清除这台设备上的全部清单勾选？')))return;checked={};document.querySelectorAll('[data-check]').forEach(el=>el.checked=false);updateChecks()};updateChecks();
const directoryUrl='https://pms.mypolycc.edu.my/index.php/hubungi-kami-2/direktori';
$('contact-list').innerHTML=`<article class="contact-card"><h3>学校总机 · PMS</h3><p>一般咨询，或请总机协助转接相关单位。</p><div class="contact-calls"><a href="tel:+6094502005">09-450 2005</a><a href="tel:+6094502006">09-450 2006</a><a href="tel:+6094502007">09-450 2007</a></div><small>来源：<a href="${directoryUrl}" target="_blank" rel="noopener noreferrer">学校官网通讯录</a><br>2026-10-02 查阅公开检索资料；拨通后请确认单位。</small></article>`+[['学生事务处 · HEP','报到、学生事务及福利问题','前往校园中心 HEP 办公区域。'],['校园警卫处','校园出入及现场安全求助','请前往警卫处；直线号码尚未核实。'],['科系办公室 · JKM / JTMK / JPH 等','课表、科系手续及学业咨询','请联系所属科系办公室，或请总机协助转接。']].map(([name,help,where])=>`<article class="contact-card"><h3>${name}</h3><p>${help}</p><p>${where}</p><small>专用电话待确认；以下为学校总机。</small><p><a href="tel:+6094502005">拨打总机 09-450 2005</a></p><a href="${directoryUrl}" target="_blank" rel="noopener noreferrer">查看官方通讯录</a></article>`).join('');
$('contact-list').innerHTML+='<article class="contact-card">'+feloMarkup()+'</article>';
const questions=[["房间设备坏了怎么办？", "迎新期间，如果房间的灯、风扇、水管、门锁等设备损坏，可以找 Felo 老师或负责的学长姐协助。说明 Block、房号和损坏情况，方便他们跟进。", null],["现在出门有巴士吗？", "目前出门可选择 Grab 或 Taxi，没有巴士服务。先确认有车接单，再安排出发；回程也记得提前约好。", null], ["哪一个 Sem 可以带车？", "可通过 SPMP 或到 HEP 申请：Sem 2 起可申请带摩托，Sem 3 起可申请带汽车。先完成申请并确认获批，再按学校要求停放。不论 Sem 几，也可选择把车停在校外停车场。但那里没有监管，车辆与财物需要自行看顾；这不等于获准把车带进校园。", null], ["男生和女生宿舍怎样分？", "男生宿舍：Block 1–5。女生宿舍：Block A–E。", "学生宿舍区"],['包裹在哪里领？','打开包裹查询报表，找到自己的姓名、订单编号和 Bakul（篮子）号；记录后前往 Bizz Mall 的 Pusat Parcel，向柜台报手机号码最后四位领取包裹。周一至四及周日 09:30–18:00；周五 09:30–12:20、14:40–18:00；周六非营业。','包裹中心'],['哪里可以打印、复印或买文具？','Café Siber（Cyber Café）在 HEP 楼下，提供文件复印及文具；Cafe Koi 店面告示也列有打印及复印服务，实际服务请向店家确认。','Café Siber'],['洗衣卡在哪里买？','提供的指南注明，在 Coop Mart 门口的洗衣卡售卖及充值机购买，RM25 包含 RM5 卡费和 RM20 余额。价格以机器显示为准。','宿舍洗衣服务'],['宿舍洗衣和 Bizz Mall 洗衣有什么不同？','宿舍洗衣设施就在宿舍内；Bizz Mall 的洗衣设施在商场旁、女生宿舍后方。两处收费和支付方式不同。','Bizz Mall 旁洗衣服务'],['外出需要带什么？最迟几点回来？','按提供的指南，需学生卡、有领衣服、长裤及包鞋。周一至周四门禁 08:00–19:00，周五至周日 08:00–22:00；周五 12:00–14:00 暂停出入。实际安排以校方通知为准。',null],['周末哪里可能没有营业？','食堂周末及假期大部分店铺可能不营业；Café Siber 周末时间待确认。Coop Mart 有周末时段，可查看地点详情。','Coop Mart'],['图书馆在哪里？','Mini Library 位于 Aras 1（1 楼）的 Bilik Studio UIDM；请从楼内前往。','图书馆'],['游泳池可以随时去吗？','不可以。泳池按日期、性别和学生／教职员分时开放，周五关闭，周末也可能因课程关闭。到访前请核对分组时间及当天安排。','游泳池']];
$('faq-list').innerHTML=questions.map(([q,a,name])=>`<details class="faq-item"><summary>${q}</summary><p>${a}</p>${name?`<button class="soft-button" data-jump="${name}">查看${name}</button>`:''}</details>`).join('');
document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{document.querySelector('[data-page="explore"]').click();$('clear-search').click();selectPlace(places.findIndex(p=>p[0]===b.dataset.jump));$('detail').scrollIntoView({behavior:'smooth',block:'start'})});
$('report-place').innerHTML=places.map(p=>`<option>${p[0]}</option>`).join('')+'<option>其他／整个网站</option>';
function openReport(name){$('report-place').value=name;$('report-result').hidden=true;$('report-status').textContent='';$('report-dialog').showModal()}
$('close-report').onclick=()=>$('report-dialog').close();
$('report-form').onsubmit=e=>{e.preventDefault();$('report-output').value=`${tr('PMS 校园指南资料反馈')}\n${tr('地点')}：${tr($('report-place').value)}\n${tr('问题类型')}：${tr($('report-kind').value)}\n${tr('日期')}：${klClock().date}\n${tr('更正内容与资料来源')}：\n${$('report-text').value.trim()}\n\n${tr('请维护者核实后更新网站。')}`;$('report-result').hidden=false;$('report-status').textContent='反馈已生成，尚未发送。请复制或分享给维护者。'};
for(const id of ['report-place','report-kind','report-text'])$(id).addEventListener('input',()=>{$('report-result').hidden=true;$('report-status').textContent=''});
$('copy-report').onclick=async()=>{try{await navigator.clipboard.writeText($('report-output').value);$('report-status').textContent='已复制，请粘贴发送给网站维护者。'}catch{$('report-output').focus();$('report-output').select();$('report-status').textContent='请长按或使用复制快捷键复制上方文本。'}};
$('share-report').onclick=async()=>{if(!navigator.share){$('report-status').textContent='此浏览器不支持分享，请复制或下载反馈文本。';return}try{await navigator.share({title:'PMS 校园指南资料反馈',text:$('report-output').value});$('report-status').textContent='已调用设备分享功能，请确认你选择的接收人。'}catch(e){$('report-status').textContent=e.name==='AbortError'?'已取消分享，反馈未自动提交。':'分享失败，请复制或下载反馈文本。'}};
$('download-report').onclick=()=>{const url=URL.createObjectURL(new Blob([$ ('report-output').value],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='PMS-feedback.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('report-status').textContent='已准备下载；请将文本文件发给网站维护者。'};
setInterval(()=>document.querySelectorAll('[data-today]').forEach(el=>{el.outerHTML=todayMarkup(el.dataset.today)}),60000);


document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>{$('clear-search').click();selectPlace(places.findIndex(p=>p[0]===b.dataset.quick));$('detail').scrollIntoView({behavior:'smooth',block:'start'})});
document.querySelector('.campus-image').addEventListener('load',()=>render());
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>render(),120)});
