let currentLanguage='en';try{const saved=localStorage.getItem('pms-language');if(['zh','en','ms'].includes(saved))currentLanguage=saved}catch{}
const translationPattern=new RegExp(Object.keys(translations).sort((a,b)=>b.length-a.length).map(s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|'),'g');
function tr(text,language=currentLanguage){if(language==='zh')return text;return text.replace(translationPattern,key=>translations[key][language]||key)}
const originalText=new WeakMap(),originalAttributes=new WeakMap();
function translatedValue(cache,current){return cache&&current===cache.applied?cache.source:current}
let translationFrame=null;
const languageObserver=new MutationObserver(()=>{if(translationFrame===null)translationFrame=requestAnimationFrame(()=>{translationFrame=null;translatePage()})});
function translatePage(){languageObserver.disconnect();document.documentElement.lang=currentLanguage==='zh'?'zh-CN':currentLanguage;document.title=tr('PMS 校园探索 — 新生指南');document.querySelectorAll('option').forEach(option=>{if(!option.hasAttribute('value'))option.setAttribute('value',option.textContent)});const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode())){const parent=node.parentElement;if(!parent||parent.closest('script,style,textarea,[data-no-translate],#language-select'))continue;const source=translatedValue(originalText.get(node),node.nodeValue),applied=tr(source);if(node.nodeValue!==applied)node.nodeValue=applied;originalText.set(node,{source,applied})}document.querySelectorAll('[alt],[aria-label],[placeholder],[title]').forEach(el=>{if(el.closest('#language-select,[data-no-translate]'))return;const entries=originalAttributes.get(el)||{};for(const name of ['alt','aria-label','placeholder','title'])if(el.hasAttribute(name)){const source=translatedValue(entries[name],el.getAttribute(name)),applied=tr(source);if(el.getAttribute(name)!==applied)el.setAttribute(name,applied);entries[name]={source,applied}}originalAttributes.set(el,entries)});document.getElementById('language-select').value=currentLanguage;languageObserver.observe(document.body,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['alt','aria-label','placeholder','title']})}
document.getElementById('language-select').addEventListener('change',e=>{currentLanguage=e.target.value;try{localStorage.setItem('pms-language',currentLanguage)}catch{}translatePage()});
translatePage();
