// Shared reading tools. Run before translation so the search index retains source text.
(()=>{
const $=s=>document.querySelector(s),all=s=>Array.from(document.querySelectorAll(s));
const text=el=>el.textContent.replace(/\s+/g,' ').trim();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let autoId=0;const ensureId=el=>el.id||(el.id='reading-item-'+(++autoId));
// Separate laundry from food; retain every service card and existing handlers.
const services=$('#daily-services'),laundry=document.createElement('div');laundry.id='laundry-services';laundry.className='lifegrid';
Array.from(services.children).filter(el=>el.querySelector('h2')?.textContent.includes('洗衣')).forEach(el=>laundry.append(el));
const laundryTitle=document.createElement('h2');laundryTitle.className='sectiontitle';laundryTitle.id='life-laundry';laundryTitle.textContent='洗衣与服务';services.after(laundryTitle,laundry);
const foodTitle=services.previousElementSibling.previousElementSibling;foodTitle.id='life-food';foodTitle.textContent='吃饭与购物';
const sportsTitle=laundry.nextElementSibling;sportsTitle.id='life-sports';sportsTitle.textContent='运动与休闲';
const sportsGrid=sportsTitle.nextElementSibling;
Array.from(sportsGrid.children).forEach(el=>{const h=el.querySelector('h2');if(h?.textContent==='校园门禁时间'){el.id='campus-gate';$('#outing-guide').prepend(el)}else if(h?.textContent==='包裹与学习资料')laundry.append(el)});
const shortcuts=document.createElement('div');shortcuts.className='life-shortcuts';shortcuts.setAttribute('role','navigation');shortcuts.setAttribute('aria-label','校园生活分类');
shortcuts.innerHTML=[['open-now','营业状态'],['life-food','吃饭与购物'],['life-laundry','洗衣与服务'],['life-sports','运动与休闲'],['outing-guide','外出篇']].map(([id,label])=>`<a href="#${id}">${label}</a>`).join('');$('#life .intro').after(shortcuts);
// Source labels describe provenance, not a new verification claim.
function badge(el,label,kind='experience'){const span=document.createElement('span');span.className='source-badge '+kind;span.textContent=label;const h=el.querySelector('h2,h3,h4');if(h)h.after(span);else el.prepend(span)}
all('#guide .guide-block').forEach(el=>{if(['checklist','contacts','student-systems'].includes(el.id))return;badge(el,'学长姐分享')});
all('#guide .club-category').forEach(el=>badge(el,'学长姐分享'));
all('#about .article').filter(el=>el.querySelector('a[href*="pms.mypolycc.edu.my"]')).forEach(el=>badge(el,'校方资料 · 见官网来源','official'));
all('#daily-services .article,#laundry-services .article').forEach(el=>badge(el,'维护者提供'));
const pool=$('#pool-guide');if(pool)badge(pool,'现场告示照片','notice');
all('#outing-guide .outing-feature').forEach(el=>badge(el,'学长姐分享'));
const sourceHelp=document.createElement('details');sourceHelp.className='source-key';sourceHelp.innerHTML='<summary>资料来源怎么看？</summary><p>校方资料：依据链接中的校方资料整理，最新安排请查看原页面。学长姐分享：同学的经验或建议，不代表校方规定。待确认：资料尚未补齐，不表示设施没有开放。</p>';$('#guide .intro').after(sourceHelp);
// Keep the primary reminder visible; fold long supporting material.
function fold(el){if(!el)return;const children=Array.from(el.children);const heading=children.find(n=>/^H[234]$/.test(n.tagName));if(!heading)return;const lead=children.find(n=>n.tagName==='P'&&!n.classList.contains('detail-source'));const content=children.filter(n=>n!==heading&&n!==lead&&!n.classList.contains('source-badge'));if(!content.length)return;const details=document.createElement('details');details.className='reading-details';const summary=document.createElement('summary');summary.textContent='展开详细说明';details.append(summary);content.forEach(n=>details.append(n));el.append(details)}
['hostel-blocks','hostel-facilities','campus-network','timetable-guide'].forEach(id=>fold(document.getElementById(id)));
all('#hostel-living .hostel-tips article').forEach((el,i)=>{if(i>0)fold(el)});
// Consolidate repeated vehicle/parking instructions into the main guide.
const transport=$('#outing-transport');transport.querySelectorAll('h3').forEach(h=>{if(h.textContent==='想带摩托或汽车来学校？'){const p=h.nextElementSibling;p.remove();h.remove()}});transport.querySelector('.outing-tip')?.remove();const vehicleLink=document.createElement('button');vehicleLink.type='button';vehicleLink.className='soft-button';vehicleLink.dataset.readTarget='hostel-blocks';vehicleLink.textContent='查看带车申请与校外停车说明';transport.append(vehicleLink);
// Download a self-contained text guide in the currently selected language.
const offline=document.createElement('div');offline.className='offline-entry';offline.innerHTML='<div><strong>随身离线小指南</strong><p>保存报到、宿舍、课表与常用入口，没网络时也能查看。</p></div><button type="button" class="soft-button" id="download-pocket">下载离线指南</button><span id="pocket-status" role="status"></span>';$('#guide .guide-sidebar').append(offline);
const offlineIds=['arrival-route','orientation-clothes','hostel-blocks','hostel-facilities','hostel-living','holiday-departure','campus-network','mobile-signal','student-systems','timetable-guide','contacts'];
$('#download-pocket').onclick=()=>{try{const parts=offlineIds.map(id=>{const copy=document.getElementById(id).cloneNode(true);copy.querySelectorAll('button,figure,img,iframe,input').forEach(n=>n.remove());copy.querySelectorAll('details').forEach(n=>n.open=true);copy.querySelectorAll('a').forEach(a=>{if(a.getAttribute('href')?.startsWith('#'))a.removeAttribute('href');else if(a.hasAttribute('href'))a.href=new URL(a.getAttribute('href'),location.href).href});return copy.outerHTML}).join('');const title=tr('PMS 随身指南'),date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuala_Lumpur',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const html=`<!doctype html><html lang="${currentLanguage}"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>body{max-width:850px;margin:24px auto;padding:0 20px;font:16px/1.8 system-ui,sans-serif;color:#15334d}h1,h2,h3{line-height:1.4}section{margin:25px 0;padding-top:12px;border-top:1px solid #cedce5}a{color:#087d80;overflow-wrap:anywhere}table{border-collapse:collapse;width:100%}th,td{border:1px solid #cedce5;padding:10px;text-align:left}.source-badge,.detail-source,.updated-meta,small{font-size:13px;color:#52697d}.reading-details>summary{display:none}@media print{body{max-width:none}a{color:inherit}section{break-inside:auto}}</style><body><h1>${esc(title)}</h1><p>${esc(tr('保存日期'))}：${date}</p><p>${esc(tr('离线文件保存的是下载时资料；外部链接需要联网。最新安排请查看网站与校方通知。'))}</p>${parts}</body></html>`;const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`PMS-pocket-guide-${currentLanguage}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);$('#pocket-status').textContent=tr('已准备下载，请在设备的下载列表保存文件。')}catch{$('#pocket-status').textContent=tr('下载失败，请重试。')}};
// Build a small local index. No queries leave the browser.
const pages={explore:'校园地图',guide:'新生指南',life:'校园生活',about:'认识 PMS'};
const records=places.map((p,i)=>({title:p[0],body:[p[4],p[5],locationHints[p[0]]||'',searchAliases[p[0]]||''].join(' '),page:'explore',place:i}));
const selector='#guide .guide-block,#guide .club-card,#life .article,#life .outing-place,#life .outing-feature,#about .article,#about .guide-block';
all(selector).forEach(el=>{const heading=el.querySelector('h2,h3,h4');if(!heading)return;records.push({title:text(heading),body:text(el),page:el.closest('.page').id,target:ensureId(el)})});
const searchButton=document.createElement('button');searchButton.type='button';searchButton.className='global-search-button';searchButton.textContent='全站搜索';searchButton.setAttribute('aria-haspopup','dialog');$('header .language-control').before(searchButton);
const dialog=document.createElement('dialog');dialog.id='global-search-dialog';dialog.className='global-search-dialog';dialog.setAttribute('aria-labelledby','global-search-title');dialog.innerHTML='<div class="search-dialog-top"><h2 id="global-search-title">全站搜索</h2><button type="button" id="close-global-search" class="soft-button">关闭</button></div><label for="global-search-input">搜索地点、指南或学会</label><input type="search" id="global-search-input" placeholder="例如：离校、PA、剪头发、学会" autocomplete="off"><p id="global-search-count" role="status"></p><div id="global-search-results"></div>';document.body.append(dialog);
const synonyms=[['剪头发','剪发','理发','haircut','salon'],['离校','放假','leave','holiday','cuti'],['pa','班主任','学业顾问','academic adviser','penasihat'],['学会','社团','club','kelab'],['复印','打印','printing','cetak'],['课表','timetable','jadual']];
const normal=s=>s.normalize('NFKC').toLowerCase();
function contains(haystack,query){if(/^[a-z0-9]{1,3}$/.test(query))return new RegExp('(^|[^a-z0-9])'+query+'([^a-z0-9]|$)').test(haystack);return haystack.includes(query)}
function search(){const query=normal($('#global-search-input').value.trim());const container=$('#global-search-results');container.replaceChildren();if(!query){$('#global-search-count').textContent=tr('输入关键词，查找全站资料。');return}const alternatives=new Set([query]);synonyms.filter(group=>group.some(w=>normal(w)===query)).forEach(group=>group.forEach(w=>alternatives.add(normal(w))));const matches=records.map((r,i)=>{const title=normal([r.title,tr(r.title,'en'),tr(r.title,'ms')].join(' ')),body=normal([r.body,tr(r.body,'en'),tr(r.body,'ms')].join(' '));const score=Array.from(alternatives).reduce((n,q)=>Math.max(n,contains(title,q)?3:contains(body,q)?1:0),0);return {r,i,score}}).filter(x=>x.score).sort((a,b)=>b.score-a.score);$('#global-search-count').textContent=matches.length?`${tr('找到结果')}：${matches.length}${matches.length>30?' · '+tr('显示前 30 项，请缩小关键词范围。'):''}`:tr('没有找到相关内容，请换一个关键词。');matches.slice(0,30).forEach(({r,i})=>{const b=document.createElement('button');b.type='button';b.className='global-search-result';b.dataset.result=i;const small=document.createElement('small'),title=document.createElement('strong'),preview=document.createElement('span');small.textContent=tr(pages[r.page]);title.textContent=tr(r.title);preview.textContent=tr(r.body).slice(0,120);b.append(small,title,preview);container.append(b)})}
let scrollBefore='';searchButton.onclick=()=>{scrollBefore=document.body.style.overflow;document.body.style.overflow='hidden';dialog.showModal();search();$('#global-search-input').focus()};$('#close-global-search').onclick=()=>dialog.close();dialog.addEventListener('close',()=>document.body.style.overflow=scrollBefore);$('#global-search-input').addEventListener('input',search);$('#language-select').addEventListener('change',()=>{if(dialog.open)requestAnimationFrame(search)});
function reveal(target){if(!target)return;for(let p=target;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;target.querySelector(':scope > details.reading-details')?.setAttribute('open','');requestAnimationFrame(()=>{target.scrollIntoView({block:'start',behavior:'instant'});target.setAttribute('tabindex','-1');target.focus({preventScroll:true})})}
function jump(id){const target=document.getElementById(id);if(!target)return;$(`[data-page="${target.closest('.page').id}"]`).click();reveal(target)}
$('#global-search-results').onclick=e=>{const b=e.target.closest('[data-result]');if(!b)return;const r=records[Number(b.dataset.result)];dialog.close();$(`[data-page="${r.page}"]`).click();if(r.place!==undefined){$('#clear-search').click();selectPlace(r.place);reveal($('#detail'))}else reveal(document.getElementById(r.target))};
document.addEventListener('click',e=>{const b=e.target.closest('[data-read-target]');if(b)jump(b.dataset.readTarget);const a=e.target.closest('a[href^="#"]');if(a){const target=document.getElementById(a.hash.slice(1));if(target?.closest('.page')){e.preventDefault();jump(target.id)}}});
const top=document.createElement('button');top.type='button';top.className='back-to-top';top.textContent='返回顶部';top.hidden=true;top.onclick=()=>{window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})};document.body.append(top);window.addEventListener('scroll',()=>top.hidden=window.scrollY<650,{passive:true});
})();
